---
- name: 'Configure and start vector'
  hosts: 'all'
  gather_facts: true
  become: true

  tasks:

    - name: 'Start and enable the vector service'
      ansible.builtin.systemd:
        name: 'vector'
        state: 'started'
        enabled: true
        daemon_reload: true
